### ISSUE TITLE
Does not generate FOMC calendar and FF rate probability distribution until the end of the year

### ISSUE THREAD

**Issue by userBCH** [ARahimiQuant/pyfedwatch#1]
FED has not yet published the calendar of FOMC meetings for 2025 (they usually do it in late summer). Because of the way ending_no_fomc is calculated the calendar would only extend until the last non-FOMC month in 2024, i.e. October. As a result, the program does not calculate probability distributions for November and December 2024.

**Comment by ARahimiQuant** [comment]
Providing the FOMC calender is out of the scope of pyfedwatch. You need to come up with the calender to be able to use pyfedwatch, as mentioned in the readme!

"The scope of PyFedWatch is focused solely on the implementation of the FedWatch methodology. Providing the fed funds futures pricing data and FOMC meetings data is beyond the scope of this package. However, we have included sample data to demonstrate how the package can be used in practice. The package does not offer up-to-date data preparation as part of its functionality."
