### ISSUE TITLE
Does this code work with Python 3.9?

### ISSUE THREAD

**Issue by phatstadt** [ARahimiQuant/pyfedwatch#2]
I am getting errors trying to instantiate a FOMC class with watch date of 2024-11-07 and a list of dates in %Y-%m-%d format for the next 8 FOMC meetings.
The code fails to find No-FOMC Month due to what appears to be issues when comparing %Y-%m strings

**Comment by phatstadt** [comment]
Found the problem. The FOMC dates provided must include at least one month with no FOMC meeting.

**Comment by ARahimiQuant** [comment]
> Found the problem. The FOMC dates provided must include at least one month with no FOMC meeting.

Well Done!
